### ISSUE TITLE
Gno.land Developer Call Agenda {23.08.2023} #12

### ISSUE THREAD

**Issue by michelleellen** [gnolang/meetings#27]
![image](https://github.com/gnolang/meetings/assets/117160070/c75fb120-3906-4bab-8c63-2df7a2d5f5d0)

### Description
Join Gnolang's core tech team and partners for the bi-weekly developer call, a regular sync with Gnolang developers working on the technology and community members interested in the engineering and development discussions. You can find the proposed agenda below, if you have additional technical points to discuss, please add them to this issue.

**Date: August 23rd at 5pm CEST**
Dial in details shared with core contributors (if you're interested in joining, and actively contributing to the code base, please reach out).

You can add the Developer Call to your calendar [here](https://calendar.google.com/calendar/u/0?cid=Y18xZTVlY2M4NWNhYzY3ZDBiZGE5ZDI3YWRmZjRlOTBiZDMyMjY4ZjI1YTYyMmExZGViODQyMjEwMzllODc4OWEyQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20).

### Agenda
Gno Contributor Updates

 Teritori review https://github.com/gnolang/gno/pull/1061
 Onbloc
 Berty - Gno Mobile [updated](https://github.com/gnolang/gnomobile)
 GnoIDE

Gno Team Topics

@thehowl Do we have an issue to discuss reflection?
Alternative to reflection, introspection https://github.com/gnolang/gno/issues/971 (@peter7891)

Open issue discussions:

 Discussion: META 'gno' CLI https://github.com/gnolang/gno/issues/1017 and associated https://github.com/gnolang/gno/issues/1045 (@moul @mvertes @gfanton )
 
 Discussion banker module https://github.com/gnolang/gno/issues/986 (@thehowl) maybe related by grc20 and dynamic call closure https://github.com/gnolang/gno/issues/986 (@moul )

Discussion: Rust VM (@peter7891) 

Question: The VM is no properly released back to sync pool feedback [issue 1033](https://github.com/gnolang/gno/issues/1033) (@piux2 @peter7891 @mvertes)

Discussion (RFC): moving gnovm/pkg/gnolang/precompile.go out of gnovm/pkg/gnolang/ [issue 1054](https://github.com/gnolang/gno/issues/1054) (@piux2)
 
 Discussion: another improved error handling proposal https://github.com/gnolang/gno/issues/1018 part of go proposals (@peter7891 @mvertes)

Discussion: How to ease local dev while keeping gno.land minimal? https://github.com/gnolang/gno/issues/1020#issuecomment-1683646703 (@gfanton)

Updates on Gno-js-client or TM2-js-client?

Finish pagination feature? https://github.com/gnolang/gno/pull/883

**Comment by jefft0** [comment]
Agenda items:

Update: Opened an issue with workaround for using Gno with gomobile. https://github.com/gnolang/gno/issues/1063 (@D4ryl00)

Discussion: Plans for goclient API, to support GnoMobile. https://github.com/gnolang/gno/pull/1047 (@jefft0 @gfanton)

**Comment by michelleellen** [comment]
A few notes:
Reflection meta issue and add to introspection issue, alternative to generics....
Gno client blockchainless - a VM experiment - database, file system or unique system? 
Hackerspace VM Face Off issue 
Large discussion on mobile'lizng' Gno
