### ISSUE TITLE
Gno.land Public Developer Call {20.092023} #14

### ISSUE THREAD

**Issue by michelleellen** [gnolang/meetings#31]
![image](https://github.com/gnolang/meetings/assets/117160070/535121c8-a5b6-4e88-a6d9-432bc15464a9)

### Description
Join Gnolang's core tech team and partners for the bi-weekly developer call, a regular sync with Gnolang developers working on the technology and community members interested in the engineering and development discussions. You can find the proposed agenda below, if you have additional technical points to discuss, please add them to this issue.

**Date: September 20th at 5pm CEST (only one hour today)**
Dial in details shared with core contributors (if you're interested in joining, and actively contributing to the code base, please reach out

You can add the Developer Call to your calendar [here](https://calendar.google.com/calendar/u/0?cid=Y18xZTVlY2M4NWNhYzY3ZDBiZGE5ZDI3YWRmZjRlOTBiZDMyMjY4ZjI1YTYyMmExZGViODQyMjEwMzllODc4OWEyQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20).

### Agenda

**Gno Contributor Updates**

[Teritori](https://github.com/gnolang/hackerspace/issues/7)
Onbloc 
[Berty ](https://github.com/gnolang/hackerspace/issues/28)- Gno Mobile 
GnoIDE 
[Flippando introduction](https://github.com/gnolang/hackerspace/issues/33) (Dragos)

**Gno Team Topics**

_GnoVM:_
New finds @thehowl 
[Issue #1135](https://github.com/gnolang/gno/issues/1135) for loops maintain the same block on iteration, which is referenced in any closures generated within 
[Issue 1136](https://github.com/gnolang/gno/issues/1136) can't append nil to a slice of interfaces 
[Issue 1148](https://github.com/gnolang/gno/issues/1148) division by zero panics cannot be recovered 
[[Issue #1149 ]](https://github.com/gnolang/gno/issues/1149) in append([]T, ...T), constant types are not converted to T implicitly 
[Issue 1150](https://github.com/gnolang/gno/issues/1150) infinitesimal non-zero float values are rejected by the preprocessor
[Issue 1151](https://github.com/gnolang/gno/issues/1151) floats not allowed in inc/dec statements linked to [[PR](https://github.com/gnolang/gno/pull/1153)] feat(stdlibs): add math and math/bits (to be reviewed)
[Issue #1152](https://github.com/gnolang/gno/issues/1152) mixing untyped (negative) floats and integers in arithmetic sometimes drops the sign
[Issue #1155](https://github.com/gnolang/gno/issues/1155) can't use unexported struct fields when converting using gno2go
_From last time, any updates?_
https://github.com/gnolang/gno/issues/1082 cryptic error: v := f(), when f returns no values, panics with evalStaticTypeOf() only supports *CallExpr with 1 result 
https://github.com/gnolang/gno/issues/1083 boolean operators (||, &&) allowed in return values (for non-boolean return values) 
https://github.com/gnolang/gno/issues/1084 test files cannot contain a tests variable (@thehowl)
https://github.com/gnolang/gno/issues/1085 conversion to uint64 is bounded to int64 values (when passing as a literal) #1085 
https://github.com/gnolang/gno/issues/1086 gnovm doesn't perform terminating statement analysis 
☝️ finds are from the gnochess application build 
https://github.com/gnolang/gno/issues/1157 amino and protobuf comments

Rust or Go VM updates (@mvertes @peter7891) - VM face off issue?
Question: status on multi-sig? 
[Issue #1106](https://github.com/gnolang/gno/issues/1106) Gno.land Fee Parameters (@MichaelFrazzy @moul)
[Issue #1101](https://github.com/gnolang/gno/issues/1101) new integration test method for Gno.land @moul and [Issue #1117](https://github.com/gnolang/gno/pull/1117) wip: add txtar driver for gnoland integration test related to @gfanton 
Plus Update on [[Gno Go client](https://github.com/gnolang/gno/pull/1047) ]feat: add gno.land/pkg/gnoclient (Gno.land Go client)
[Issue #1108](https://github.com/gnolang/gno/issues/1108) The Portal Loop @moul

**Comment by jefft0** [comment]
If there is time, to discuss this issue for how amino can include doc comments in the protobuf output. https://github.com/gnolang/gno/issues/1157
